---
# tasks file for tsuru_api

- name: Add tsuru repositories.
  apt_repository: repo='ppa:tsuru/ppa' update_cache=yes

- name: Install packages.
  apt: update_cache=true name="{{ item }}"
  with_items:
    - python-software-properties
    - "{% if tsuru_server_version is defined %}tsuru-server={{ tsuru_server_version }}{% else %}tsuru-server{% endif %}"
    - "{% if tsuru_admin_version is defined %}tsuru-admin={{ tsuru_admin_version }}{% else %}tsuru-admin{% endif %}"
    - "{% if tsuru_client_version is defined %}tsuru-client={{ tsuru_client_version }}{% else %}tsuru-client{% endif %}"

- name: Copy configuration file.
  template: src=tsuru.conf.j2 dest=/etc/tsuru/tsuru.conf
  notify:
    - restart tsuru_api

- name: Copy tsuru-server file.
  template: src=tsuru-server.j2 dest=/etc/default/tsuru-server
  notify:
    - restart tsuru_api

- name: Start tsuru_api
  service: name=tsuru-server-api state=started

# Remove target first otherwise add will fail.
# Note that remove target does not fail if target exists
- name: Configure tsuru-admin command.
  shell: >
    tsuru-admin target-remove local;
    tsuru-admin target-add local http://127.0.0.1:{{ tsuru_api_listen_port }} -s

- name: Wait for tsuru-server to be up
  wait_for: port={{ tsuru_api_listen_port }} timeout=60
